name: Release and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    defaults:
      run:
        working-directory: ./seedling

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Install pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "./seedling/pnpm-lock.yaml"

      - run: pnpm install
      - run: pnpm run prepublishOnly

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
